### ISSUE TITLE
mouse click for selection does not make much sense

### ISSUE THREAD

**Issue by Wladefant** [personalizedrefrigerator/js-draw#29]
Everything in the toolbar was clear or almost clear for me, except the mouse

I was not sure what it was, clicked on it and through trying understood that it was the selction tool.
The desiign convention for selection is this dotted line and i would suggest we use it.
![SmartSelect_20230919_001622_Samsung Notes](https://github.com/personalizedrefrigerator/js-draw/assets/79611093/a3a6304a-b2c9-477c-ba3a-de412634877d)

**Comment by personalizedrefrigerator** [comment]
Thank you for the feedback!

`js-draw`'s icons are currently based on the [Material Icon Pack](https://fonts.google.com/icons?icon.query=select) from Google. Here are two similar icons from that pack:

[`select`](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aselect%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048):
![Icon: Dashed rectangle](https://github.com/personalizedrefrigerator/js-draw/assets/46334387/66d46e46-da8d-4b80-8852-c8403113fb63)

[`gesture_select`](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Agesture_select%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048):
![Icon: Pointing hand over dashed rectangle](https://github.com/personalizedrefrigerator/js-draw/assets/46334387/157a09ae-761f-4b4e-9989-5c622b7c4b53)

I selected rectangular selection icons because `js-draw` doesn't support lasso selection (though it is something I would like to eventually implement).

Note that Joplin is sponsoring development of `js-draw` and has @MartaLC reviewing and creating a design for the app UI. [The design can be found here](https://www.figma.com/file/NA5F2AMWO3wUuaoDfUaAb8/JS-Draw--Material-3-wireframes?type=design&node-id=54879-404&mode=design&t=iZ5ODkttbDZssd1p-0). Feel free to leave design-related comments there as well!

**Comment by Wladefant** [comment]
For future reference I will leave the link for the lasso select [HERE](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alasso_select%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024). Lasso select is definitely a needed feature even though not priority number one. 

These icons are for sure much better. I would prefer

**Comment by personalizedrefrigerator** [comment]
Resolved in a8b3b5644355a77bfd61ee8e4142d05d6e355268

**Comment by Wladefant** [comment]
Nice @personalizedrefrigerator which one did you choose?

**Comment by personalizedrefrigerator** [comment]
I chose

[`select`](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aselect%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048):
![Icon: Dashed rectangle](https://github.com/personalizedrefrigerator/js-draw/assets/46334387/66d46e46-da8d-4b80-8852-c8403113fb63)

I've also received some feedback about how `Exit` and `Save` behave (that "Save" shouldn't close the editor, see the Figma file). I plan to build/release a new Android version after making this Save/Exit change.

**Comment by personalizedrefrigerator** [comment]
I chose

[`select`](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aselect%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048):
![Icon: Dashed rectangle](https://github.com/personalizedrefrigerator/js-draw/assets/46334387/66d46e46-da8d-4b80-8852-c8403113fb63)

I've also received some feedback about how `Exit` and `Save` behave (that "Save" shouldn't close the editor, see the Figma file). I plan to build/release a new Android version after making this Save/Exit change.

**Comment by Wladefant** [comment]
> chose\n\nselect:\n

Yes that is the one I am talking about
